[package]
name = "minigit"
version = "0.1.0"
edition = "2021"

[lib]
name = "minigit"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
sha1 = "0.10.6"
